{"@t":"2024-02-11T09:28:11.7271939Z","@mt":"Failed to determine the https port for redirect.","@l":"Warning","EventId":{"Id":3,"Name":"FailedToDeterminePort"},"SourceContext":"Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware","RequestId":"0HN1AR9TVH63U:00000002","RequestPath":"/api/Order/GetOrders","ConnectionId":"0HN1AR9TVH63U","ThreadId":11,"ProcessId":19552,"EnvironmentName":"Development","MachineName":"IN-PG0351Q9"}
{"@t":"2024-02-11T09:28:14.5238145Z","@mt":"An error occurred: We have No orders with registerId: 6","@l":"Error","SourceContext":"Training.User.Middleware.ExceptionHandlingMiddleware","RequestId":"0HN1AR9TVH63U:00000002","RequestPath":"/api/Order/GetOrders","ConnectionId":"0HN1AR9TVH63U","ThreadId":11,"ProcessId":19552,"EnvironmentName":"Development","MachineName":"IN-PG0351Q9"}
{"@t":"2024-02-11T09:28:15.1284996Z","@mt":"An error occurred, StackTrace:    at Training.Order.Controllers.OrderController.GetOrders(Int32 registerId) in C:\\Users\\hariomroy\\Desktop\\MySoln\\Training.Order\\Controllers\\OrderController.cs:line 46\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n--- End of stack trace from previous location ---\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)\r\n   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)\r\n   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)\r\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\r\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\r\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\r\n   at Training.User.Middleware.ExceptionHandlingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in C:\\Users\\hariomroy\\Desktop\\MySoln\\Training.Order\\Middleware\\ExceptionHandlingMiddleware.cs:line 23, Message: We have No orders with registerId: 6","@l":"Error","SourceContext":"Training.User.Middleware.ExceptionHandlingMiddleware","RequestId":"0HN1AR9TVH63U:00000002","RequestPath":"/api/Order/GetOrders","ConnectionId":"0HN1AR9TVH63U","ThreadId":11,"ProcessId":19552,"EnvironmentName":"Development","MachineName":"IN-PG0351Q9"}
